[project]
name = "ava-sae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.2",
    "datasets>=3.1.0",
    "sae-lens>=6.37.4",
    "torch>=2.10.0",
    "ipykernel",
    "matplotlib>=3.10.8",
    "sae-vis>=0.2.15",
    "safetensors==0.4.5",
    "sae-dashboard",
]
[tool.uv.sources]
torch = { index = "pytorch"}

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"

[tool.uv]
environments = ["sys_platform == 'linux'"]
